### PR TITLE
Get ready for v1.0.0

### PR DESCRIPTION
**Pull request by ghoneycutt**
Would like to move this module to v1.0.0 with the following changes
- param name: change 'tac_key' to 'key' - no reason put to 'tac_' or
  similar string prepended to variables.
- managing the init script should be optional since some packages come
  with a working init script
- managing the pam config should be optional as it is not universally
  needed
- allow for specifying a different template (such as
  'profile/tac_plus.conf.erb'. This is needed because the config
  language is so rich, that allowing for it all to be expressed within a
  template would be a huge commitment of time and effort. Teams that are
  already using tacacs likely already have their own config files and
  allowing those to be templatized as they are is a much simpler process.

### CODE REVIEW

**Comment by ghoneycutt** [comment]
Needs the following

[ ] - figure out modes, perhaps @diddi- can help by inspecting a running system
[ ] - spec tests need to be completely redone
[ ] - rubocop working
[ ] - compliant with rubocop
[ ] - README written

**Comment by Phil-Friderici** [comment]
I know this is not a stable release (aka 1.0.0) yet, but I need to check if API changes would break things in production. If so, it will be needed to add backward compatibility workarounds.
But this should not stop you from adding good stuff™.

**Comment by Phil-Friderici** [comment]
PS: for me it would be very helpfull to have the spec ready before changing functionality. Let's get that fixed when wearing my other hat ;)

**Comment by Phil-Friderici** [comment]
Wishlist:
- [ ] refactor linebreaks in tac_plus.conf template for easier testing

**Comment by Phil-Friderici** [comment]
Fixed linebreaks in https://github.com/ghoneycutt/puppet-module-tacacsplus/pull/3

**Comment by Phil-Friderici** [comment]
Spec tests for supported attributes are missing in:
- [ ] $users
- [ ] $localusers
- [ ] $groupsusers

**Comment by Phil-Friderici** [comment]
Change default value of 'NONE' to undef or {}:
- [ ] $users
- [ ] $localusers
- [ ] $groups

**Comment by Phil-Friderici** [comment]
@ghoneycutt are you aware that manage_pam is bound to VAS usage ?

**Comment by ghoneycutt** [comment]
@Phil-Friderici This is ready for merge

**Comment by ghoneycutt** [comment]
Thank you!

**Comment by Phil-Friderici** [comment]
will be release in 1.0.0 that will become available very soon

**Comment by Phil-Friderici** [comment]
Thank you too! Just released as 1.0.0 now.

**Pull request merged**
